### ISSUE TITLE
Stacks: Combining items in external inventories doesn't update the count.

### ISSUE THREAD

**Issue by jellyton255** [Bilwin/helix-plugins#2]
Combining items that are stored in a non-player inventory (like a container) [tested with containers] does not automatically update the count for some reason. (I acknowledge that this is probably an issue with the helix itself, but I thought I'd mention it)

**Comment by jellyton255** [comment]
This commit is for splitting, not combining.

**Comment by Heyter** [comment]
Solved:
`self:SetData("stacks", totalStacks, ix.inventory.Get(self.invID):GetReceivers())`

**Comment by Bilwin** [comment]
I think this solved the problem
