### ISSUE TITLE
Stacks: (InventoryItemAdded) hook

### ISSUE THREAD

**Issue by Heyter** [Bilwin/helix-plugins#5]
```
function PLUGIN:InventoryItemAdded(_, inventory, item)
	local maxStacks = item.maxStacks
	local stacks = item:GetData("stacks", 1)
	if (stacks >= maxStacks) then return end

	for _, v in pairs(inventory:GetItems()) do
		if (v.id != item.id and item.uniqueID == v.uniqueID) then
			local curStacks = v:GetData("stacks", 1)
			if (curStacks >= maxStacks) then continue end

			local totalStacks = curStacks + stacks

			if (totalStacks > maxStacks) then
				v:SetData("stacks", maxStacks)
				item:SetData("stacks", totalStacks - maxStacks)
			else
				item:Remove()
				v:SetData("stacks", totalStacks)
				break
			end
		end
	end
end
```

I'm too lazy to make a pull request

**Comment by Bilwin** [comment]
When items are split, the stack "removes", the item.data also changes to splitted value

**Comment by Heyter** [comment]
> When items are split, the stack "removes", the item.data also changes to splitted value

Буду писать на русском.
Если ты имеешь ввиду разделить стаки, то у себя я перегрузил метод INVENTORY:Add(uniqueID, quantity, data, x, y, noReplication, split) и проверяю, если это разделение, то попросту пропускаю stack. Других идей у меня нет в данный момент. Можно посмотреть как написан nutscript 1.1-beta.

```
	if (!split and (item.invID or 0) == 0 and item.isStackable) then
		if (!isnumber(uniqueID)) then -- т.к у ix.item.list нету data по дефолту
			item.data = (data or {})
		end
```
этот код я выполняю до того как буду стакать предметы.

https://paste.ofcode.org/FnKMsvnWXkUVnbct68h9Nr
По этому я сказал что наверное не стоит релизить такой стак.
